### ISSUE TITLE
Angularjs $http chain of promises with jsPanel 2

### ISSUE THREAD

**Issue by karimfikry** [Flyer53/jsPanel#13]
I'm using jsPanel to show the results of chain of promises in AngularJS project. I want to ask about how to do the chain of promises within the panel? or shall I apply it in the controller and then pass the result to jsPanel?

Thanks!

**Comment by omkargokhale** [comment]
@karimfikry did you manage to set the content html with angularjs template?

**Comment by nxhoang** [comment]
I'm wondering about how to use jsPanel with Angularjs 1x. Could you share your source code with me?
Thanks in advanced.
