### ISSUE TITLE
Resize Method

### ISSUE THREAD

**Issue by huntmur** [Flyer53/jsPanel#20]
Thanks so much --- This is a really awesome piece of code!! :)

I was wondering if you had any thoughts on resizing the panel as a method after the panel has been created?

if i use, var tp = $.jsPanel();
-and then-
tp.css({'width':'500', 'height':'300'});

The content div has an unresized border until I use the resize control or max or min etc the panel - so it looks like .css wont be an option.

Anyway, just wondering if there is a work around or any plans on adding a resize method? :)

I can provide more detail if needed.

Thanks again,
Jim

**Comment by gbaumgart** [comment]
hi, is there a 'resized' event or similar in beta-3 ? I can't find anything related.

**Comment by Flyer53** [comment]
Hi there,

It depends.

If the panel is resized using the resize handle you can use the "stop"
event from jquery ui resizable:
http://api.jqueryui.com/resizable/#event-stop

The resize method does not fire an event yet. Might be a good idea to add
one ... let me think about this ...

2016-03-21 11:48 GMT+01:00 gbaumgart <notifications@github.com>:

> hi, is there a 'resized' event or similar in beta-3 ? I can't find
> anything related.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Flyer53/jsPanel/issues/20#issuecomment-199222610>
>



-- 
Stefan Sträßer
flych53g@gmail.com
http://stefanstraesser.eu/
http://jspanel.de/ <http://stefanstraesser.com/>

**Comment by gbaumgart** [comment]
Hi Stefan,
yes, it seems a little chaotic, I need to pass in options: onmaximized, onnormalized and then panel.on('resize') to tell my app the same.

**Comment by Flyer53** [comment]
Hold it ...

forgot a little detail from my own code ;)

When a jsPanel is resized using the method resize() the jquery ui
"resizestop" event is triggered after resizing. So you can do something
like:

var test = $.jsPanel({id: "testpanel"});

test.on( "resizestop", function(event, ui) {
  console.log(event.type + " triggered by " + test.attr('id'));
});

test.resize(500, 500);

2016-03-21 11:48 GMT+01:00 gbaumgart <notifications@github.com>:

> hi, is there a 'resized' event or similar in beta-3 ? I can't find
> anything related.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Flyer53/jsPanel/issues/20#issuecomment-199222610>
>



-- 
Stefan Sträßer
flych53g@gmail.com
http://stefanstraesser.eu/
http://jspanel.de/ <http://stefanstraesser.com/>

**Comment by Flyer53** [comment]
Looks like you could use something like **option.onresizestop** ?
I'll see whether I can get this in with the next beta update. How about that?

**Comment by gbaumgart** [comment]
fine with me :-) However, its not that important to me, got it working with the callbacks in options. 

But yeah, actually I'd suggest this events: 'onResizeBegin', 'onResizing' and ''onResizeEnd' or similar, just to make it complete. I've good use for all of them.

**Comment by Flyer53** [comment]
Just updated the beta once more and added **option.onbeforeresize** and **option.onresized**. But callbacks assigned to these two options only execute if the resizing operation was started by the method **.resize()**.

For callbacks to execute on resize operations done by the user with the mouse use the events **start**, **resize** and **stop** provided by the jquery ui resizable interaction. http://api.jqueryui.com/resizable/
You can add such a callback to your panel config using **option.resizable** like:
```javascript
$.jsPanel({
  resizable: {
    start: function(event, ui) {
      // whatever to do ...
    },
    resize: function(event, ui) {
      // whatever to do ...
    },
    stop: function(event, ui){
      $('.jsPanel-content', ui.element).append("panel was resized !");
    }
  },
  // more panel config ...
});
```
I think this gives you about everything you need?

**Comment by gbaumgart** [comment]
ups, didn't saw it. yes! that will do!
