### ISSUE TITLE
Add a configurable default for the offset of a maximized window

### ISSUE THREAD

**Issue by bryangreen** [Flyer53/jsPanel#21]
Extend the default object to include an offset parameter for the maximized window. 

The new parameter could be called *maximizedOffset* and take an object like the current *offset* parameter.

For instance:
```
maximizedOffset:{
  top: 95,
  bottom: 40
}
```
The maximized panel would essentially have an additional top margin of 95 and bottom margin of 40 pixels.

The default settings according to *calcPosmaxtoScreen* would be:
```
maximizedOffset:{
  top: 5,
  left: 5
}
```

**Comment by Flyer53** [comment]
@bryangreen 
Hi Bryan, thanks for your input.
Let me check whether I get you wright? Hitting the maximize button of a jsPanel would result in a panel with something like:
+ position top: 100px
+ panel height: 100% - 145px
+ panel width: standard maximized width

Or in other words: You want a maximized panel that is not fully maximized but leaves some configurable space at the top and bottom of the viewport. Am I correct?

Would you mind sharing why you want this special "maximize behaviour".

Stefan

**Comment by Flyer53** [comment]
@bryangreen 
If my understanding of your idea is correct you could achieve this already by use of the **jspanelmaximized** event. The example below is for a jsPanel appended to the body element.
```javascript
var myPanel = $.jsPanel();
myPanel.on('jspanelmaximized', function (event, id) {
    myPanel.css('top', function () {
      return parseInt(myPanel.css('top')) + 100 + 'px';
    });
    myPanel.resize(null, function () {
      return $(window).height() - 145 + 'px';
    });
});
```
The **resize()** method is new in version 2.3.0

**Comment by bryangreen** [comment]
@Flyer53 
You are correct in your interpretation of what I'd like to see when the panel is maximized. I'd like to target the maximize to the body element.
I tried out the maximized event code you wrote and it does work. 

Unfortunately, the maximize animation initially maximizes the window and then the panel awkwardly shifts down and resizes.

Alternatively, the maximize position code needs to take into account fixed elements. For instance, I have an element fixed to the top of the screen that is used for navigation. This top navbar is covered when the jsPanel is maximized. 

Thanks for your time.

**Comment by Flyer53** [comment]
@bryangreen  You're welcome ...

Yes I know it's just a work around and really doesn't look smooth. I'll look into this again as soon as I have some time.

Thanks for your input :)

**Comment by Flyer53** [comment]
@bryangreen 
You might be pleased to read that I'm working on a version that has a new **option.maximizedMargin** with the properties **top**, **right**, **bottom**, and **left** doing exactly what you asked for. Example:
```javascript
var myPanel = $.jsPanel({
    maximizedMargin: {
        top: 100,
        bottom: 50
    }
});
```
All margins not set will default to 5px.

If all goes well this will be in version 2.4.0 and I let you know when I have a Beta for you to test.

**Comment by Flyer53** [comment]
@bryangreen 

http://beta.jspanel.de/api.html?link=option-maximizedMargin

**Comment by bryangreen** [comment]
@Flyer53 
This is great! I'm looking forward to giving this a shot -- example is spot-on.
I'd be glad to beta test this enhancement in a few environements.
Bravo, Stefan.

**Comment by Flyer53** [comment]
@bryangreen 

Below is a link to download the version 2.4.0 beta. Consider one more change that might be of relevance in case you use header and/or footer toolbars:

I changed the css of the header section, header toolbar and footer toolbar effectively making them **flexbox-containers**. So it could be that you have to make changes to your toolbars. But in the end it makes it a lot easier I think.

Grab the beta here: http://jspanel.de/downloads/jspanel-2.4.0Beta.zip

Looking forward to your feedback ... :)

**Comment by Flyer53** [comment]
@bryangreen 
**The current 2.4.0 beta doesn't use any flexbox features any more.**

**Comment by mikeimhof** [comment]
I really love your tool.  Do  you have an example of the resize event handler?  I could not find it but I want to utilize it.  

Thanks,  Mike

**Comment by Flyer53** [comment]
Hi Mike,
thanks a lot for the praise :)

Well, jsPanel doesn't have its own resize event because it's provided by the jQuery UI Resizable Interaction already and you can configure a resize callback within **option.resizable**. The following example uses the **resizestop** event to log the new size to the panel content after resizing:
```javascript
$.jsPanel({
  resizable: {
    stop: function(event, ui) {
      $(".jsPanel-content", ui.element).append("width: " + ui.size.width + "<br>height: " + ui.size.height + "<br>");
    }
  }

});
```
Read more about jQuery UI Resizable events at http://api.jqueryui.com/resizable/

Hope this helps. Otherwise ask again, Stefan

**Comment by mikeimhof** [comment]
Thanks!  again, love your tool :)
