### ISSUE TITLE
console.log not working in IE8

### ISSUE THREAD

**Issue by gdevilee** [Flyer53/jsPanel#22]
console.log not working in IE8

line: 62
line: 1771
line: 1772

**Comment by Flyer53** [comment]
That's no surprise and you can find a lot about this searching for console and IE8. For eaxample:

http://stackoverflow.com/questions/22103156/console-log-in-ie8
http://stackoverflow.com/questions/2656730/internet-explorer-console
http://stackoverflow.com/questions/7742781/why-javascript-only-works-after-opening-developer-tools-in-ie-once

Another issue might be the jQuery version you use. As of jQuery 2.x IE less than 9 is not supported any more.

And in general I don't make any effort with jsPanel to support such an old browser. Sorry!
