### ISSUE TITLE
panel changes width with initial height decrease/increase 

### ISSUE THREAD

**Issue by schalivendri** [Flyer53/jsPanel#24]
Panel changes width with initial height decrease/increase when '.ui-resizable-s' is dragged.

**Comment by Flyer53** [comment]
Could you please give me the example where this happens! I know I had this once, but thought I've fixed it. What jsPanel version are you using? And perhaps you want to try the 2.4.0 Beta http://beta.jspanel.de/downloads/jsPanel-2.4.0.zip

**Comment by Flyer53** [comment]
Well, seems like I fixed that only in the 2.4.0 Beta. But the beta is quite save to use now, although it's not released yet. I won't do any changes to the exsisting api. If you don't mind check it out and tell me what you think.http://beta.jspanel.de/

**Comment by schalivendri** [comment]
Thanks for the response.
The issue doesn't seem to happen in 2.4.0 Beta. But it can be reproduced in the examples at http://jspanel.de/api/jspanelfunction by dragging the bottom of JsPanel to increase the height.

**Comment by Flyer53** [comment]
You're absolutely correct. Could you live with it being fixed in 2.4.0?

**Comment by schalivendri** [comment]
Thanks again. I cannot use beta version, So I have to wait until the stable version.
For now, I am just hiding the '.ui-resizable-s', but the issue can still be reproduced when the panel is resized(lower right drag icon) by just increasing height.
Any idea on when the next stable version will be out?

**Comment by Flyer53** [comment]
Well I'm quite sure that I can release 2.4.0 within this month. For the time being I suggest that you add **option.resizable** to your panel your config like:
```javascript
$.jsPanel({
    resizable: {
      handles: "nw, ne, se, sw" // or remove whatever corner you don't need
    }
});
```
This would disable the sides for resizing and only enables the corners. And you don't need to hide anything.

For a lot more resizable options please refer to http://api.jqueryui.com/resizable

**Comment by schalivendri** [comment]
Sure, I will use the handles property. Looking forward to use 2.4.0.
Thanks a lot for your effort!

**Comment by Flyer53** [comment]
You're welcome. If I can be of help, don't hesitate to write.

**Comment by Flyer53** [comment]
@schalivendri 
I just found out that the error you reported only happens when using the minified jsPanel script. When I use the unminified version everything seems to be ok. Would you mind checking that in your environment and give ma a feedback? Thanks in advance :)

**Comment by Flyer53** [comment]
@schalivendri 
Just updated the 2.3.x branch to version 2.3.4. Only change is a replacement of the minified javascript file. So there shouldn't be any more problems with resizing.

**Comment by schalivendri** [comment]
@Flyer53 
Thanks alot for your time and effort.
I was using 2.3.3 unminified version and had issue. I updated to 2.3.4 unminified version and issue seems to be resolved. I compared these two versions, 2.3.3 version has width: '100%' in resizeContent whereas 2.3.4 has been updated with  width: panel.outerWidth() + 'px' in resizeContent.
This might have fixed the issue.
