### ISSUE TITLE
Issue when the panel is in minimized state

### ISSUE THREAD

**Issue by Uma19** [Flyer53/jsPanel#27]
Hi Guys,

First thing Really hats off to you guys to build such a nice panel :)

Currently I am using this version of jspanel 2.3.4
and using that I was facing the below issue : please find the steps below 
Step 1) In my application I m using 2 panels. 
Step 2) My 1st panel is in minimized state and positioned @rightbottom
Step 3) My 2nd panel is positioned in some other position.
Step 4) now when my 2nd panel give a call to close function, it animates my first panel to @leftBottom automaticlly.

Reason : when it closes any panel then it gives a call to the "reposMinimized" function where it sets the left postion of the minimized state panels
Solution : So what I think is in "reposMinimized" function : we should check i <= minimizedCount instead of i < minimizedCount, since it sets the left postion of the respective panel to 0px if the for loop states from 0.

Please find below the corrected code.
        // repositions minimized jsPanels
        reposMinimized: function () {
            var minimized = $('#jsPanel-min-container > .jsPanel'),
                minimizedCount = minimized.length,
                i;
            for (i = 0; i <= minimizedCount; i += 1) {
                minimized.eq(i).animate({
                    left: (i * jsPanel.widthForMinimized) + 'px'
                });
            }
        },

So in my code I have incoorperate the above changes and it worked :)
Let me know if it contains any other side effect

**Comment by Flyer53** [comment]
Hi there,

thanks a lot for the praise and your input. I do appreciate that very much :)

But before I make a change to version 2.3.4 please note that I'm about to release version 2.4.0 within the next days and there **repositionMinimized()** is rewritten as follows:
```javascript
reposMinimized: function () {
    $('.jsPanel', '#jsPanel-min-container').each(function(index, elmt){
        $(elmt).animate({
            left: (index * jsPanel.widthForMinimized) + 'px'
        });
    });
}
```
That's a lot easier and the function doesn't need the former for loop anymore.

Check out the 2.4.0 beta here: http://beta.jspanel.de
and download here: http://beta.jspanel.de/downloads/jsPanel-2.4.0.zip

**Comment by Uma19** [comment]
Hello,

That's great and will make use of this version (y)
