### ISSUE TITLE
Links in panels ajax not clickable

### ISSUE THREAD

**Issue by Mick89** [Flyer53/jsPanel#28]
The links in the panels ajax are not clickable for version 2.4.0

$('#btn3').click(function () {
	"use strict";
	$.jsPanel({
		size: {width: 800, height: 400},
		position: {left: "center", top: 10},
		theme:    "success",
		load: {
			url: 'ajaxFile.html',
			complete: function(response, status, xhr, jsPanel){
				//console.log( status );
			}
		}
	});
});

In ajaxFile.html
< a href=" http:// www . domain. com " target="_blank" >lien </a>

**Comment by Flyer53** [comment]
Hi there,

please read the following blog. Than you know why and how to handle this problem.

http://blog.codebusters.pl/en/click-doesn-t-work-after-ajax-load-jquery

**Comment by Mick89** [comment]
Hi,

Thank you for your very good work.

There is a change in the version 2.4.0 which causes this problem? I do not have a problem with the previous versions 2.3.0.

Thanks again!
Mick

**Comment by Flyer53** [comment]
Hi Mick,
your welcome, and thanks for your input :)

Well, the function itself that deals with option.ajax did not change from 2.3.x to 2.4.0, just the way the function is called internally is slightly different. But that shouldn't make a difference ...

But my quick google search showed that this is a pretty common issue with content loaded via AJAX and is not restricted to jsPanel. So actually I can't say why it happens with 2.4.0 but not with 2.3.x. I'm not aware of a change in 2.4.0 that causes this issue.

Stefan

**Comment by genachka** [comment]
@Flyer53 
I'm seeing the same issue with 2.4.1 after upgrading from 2.3.3. My code hasn't changed and when I reverted to 2.3.3 all works again.

**Comment by genachka** [comment]
@Flyer53 
I'm also using a select2 jQuery control (https://select2.github.io) in some of my jsPanels and whatever changed between 2.3.3 and 2.4.1 broke too. It no longer opens the dropdown. Possibly related to the click issue, or maybe another issue, but it definitely worked in 2.3.3 and I checked it does work outside of jsPanel just fine.

**Comment by Mick89** [comment]
If that can help to understand. The input files are not usable.

In ajaxFile.html
< input type = "file" >

Is there perhaps Return false which blocks the event?

Thanks again!

**Comment by Flyer53** [comment]
@genachka @Mick89 
Hey folks, thanks a lot for your input :)
Well I think it all relates to the same issue ... and I'm still not aware of any change in jsPanel that could cause this. But I'll try to find out of course...

Let me make some experiments myself and than I'll be back here.

Btw: the jsPanel homepage shows a version 2.4.1 but the current download is still 2.4.0. There is no release for a 2.4.1 yet.

**Comment by Flyer53** [comment]
@genachka 
I set up a quick test that creates a jsPanel, loads html containing a select element via option.ajax and uses Select2:

http://jspanel.de/documentation/test.html

As far as I can see it works fine ...

**Comment by Mick89** [comment]
Thanks!
Can you add < input type = "file" > in select2.html to check?

**Comment by Mick89** [comment]
I also have a very strange behavior with < input type="checkbox" > (in select2.html).
Impossible to maintain checked.
Can you also check?
Thanks again!

**Comment by Flyer53** [comment]
@Mick89 
I found a difference between 2.3.x and 2.4.x that might cause the problems you described. Let me make a few more tests and than I hopefully can fix this ...

**Comment by Flyer53** [comment]
@Mick89 @genachka 
Well, looks like I have to go back to 2.3.3 and gradually implement the changes from 2.4.0 in order to find the problem. Sorry folks :(

**Comment by Mick89** [comment]
No problem. I am certain that you will find the solution. You do a good job. :)

**Comment by Flyer53** [comment]
@Mick89 @genachka 
Try this one:
http://jspanel.de/downloads/jsPanel-2.4.1.zip
Not a release yet, but I think I finally found the issue behind the not working &lt;input type="file"&gt;
And http://jspanel.de/documentation/test.html has a file input as well

**Comment by genachka** [comment]
@Flyer53 
Thanks for your prompt attention to this. The 2.4.1 fixes the ajax click but not the issue with the select2. I am using select2 version 3.5.2 with an input. The ajax html that it's pulling back, also has a script in it and among other things, I'm doing in it the init for the select2 control that part of the ajax html pulled back:
`
    'use strict';

    $(document).ready(function() {
        var sampleTypes = [
            {id:0, text:'Sample1'},
            {id:1, text:'Sample2'},
            {id:2, text:'Sample3'},
            {id:3, text:'Sample4'}
        ];

        $("#sampleTypes").select2({
            data: sampleTypes.sort(),
            placeholder: "Select type",
            minimumResultsForSearch: -1,
            width: '215'
        });
    });

`

**Comment by genachka** [comment]
@Flyer53 
And in case it helps, I'm setting these for jsPanel:
`
ajax: {
                        url: url
                    },
                    id: 'mySamplePanel',
                    title: '',
                    size: {width: 1100, height: 460},
                    position: 'center',
                    theme: 'medium',
                    paneltype: {
                        type: 'modal',
                        mode: 'default'
                    },
                    controls: {iconfont: 'font-awesome'},
                    toolbarFooter: mySampleFooter
`

**Comment by Flyer53** [comment]
@genachka 
Ok, there seems to be a problem when using Select2 in combination with a modal jsPanel. Have yet to find out why ...
Otherwise it works fine. Added an example to http://jspanel.de/documentation/test.html

**Comment by Flyer53** [comment]
@genachka @Mick89 
Found it !! And modified the example accordingly showing a modal panel with Select2.
The problem is that I apply a pretty high z-index value to the modal backdrop and a modal panel to ensure that other page content is hidden by the modal backdrop. So the Select2 container was actually there, but because it doesn't have a z-index by default it was hidden "below" the modal backdrop. So I simply added a handler that responds to the **select2:open** event and applies a high z-index value to the **select2-container** like:
```javascript
$(".sampleTypes").select2({
    data: sampleTypes.sort(),
    placeholder: "Select type",
    minimumResultsForSearch: -1,
    width: '215'
 }).on("select2:open", function(){
    $(".select2-container").css("z-index", 10002);
});
```
A modal panel has a z-index of 10001. So I used 10002 for the example.
http://jspanel.de/documentation/test.html

**Comment by Flyer53** [comment]
@genachka @Mick89 
Don't forget to download http://jspanel.de/downloads/jsPanel-2.4.1.zip for testing again.

**Comment by Mick89** [comment]
It is perfect for me!
Thanks again for your serious and your reactivity! :)

**Comment by genachka** [comment]
@Flyer53 
Thanks for tracking this down. For me however, it was the z-index on .select2-drop-active that resolved it.
