### ISSUE TITLE
any way to resize in minimized/smalified state

### ISSUE THREAD

**Issue by alisabri** [Flyer53/jsPanel#29]
Hi Stefan,
Is there any way to resize a panel (which is already appended dom) as if it is created new ?
For the moment I save panel object as data(to dom) and then later trying to use object methods but no success so far. Appreciate any advice.

Regards

**Comment by alisabri** [comment]
Hi again,
I managed to make it work by totally closing current panel and creating new one with same id and new content. If there is way to make it without closing could you please comment on that direction ?

Regards

**Comment by Flyer53** [comment]
As of version 2.4.0 there is a method **resize( width, height )** available. Please refer to the API documentation for details: http://jspanel.de/api/method/resize

**resize( width, height )** can be called on jsPanels not minimized. For minimized panels it doesn't really make sense. If you want to "normalize" a minimized panel programatically you could do this like ...
```javascript
var panel = $.jsPanel();

jsPanel.normalize(panel);
```

**Comment by alisabri** [comment]
Thanks Stefan

**Comment by Flyer53** [comment]
Forget something:
To "normalize" programatically you can of course use also
```javascript
var panel = $.jsPanel();

panel.normalize();
```
