### ISSUE TITLE
In modal dialog, resize handle being displayed on bottom left

### ISSUE THREAD

**Issue by genachka** [Flyer53/jsPanel#30]
I don't have a resize enabled for the modal dialog, and even if I did I would have expected the resize handle icon to be displayed on the right. But in 2.4.0 and 2.4.1 I see a resize handle being shown on the bottom left. I'm expecting it not to be shown.

**Comment by genachka** [comment]
Also noticed in modal dialog, when moving mouse cursor to footer area, cursor changes from default to hand.

**Comment by Flyer53** [comment]
Mmmmh, did you change the css file as well?. The css for a bottom left resize handle is in there but commented out in the download file.

Cursor: Do you mean changes to a hand or changes to a move cursor? Because I see a move cursor. Has to be altered for a standard modal of course. By default the footer toolbar is also a handle to drag the panel....

**Comment by genachka** [comment]
No change directly to jsPanel css, using the default. See attached image for the two issues I see.
![jspanel footer issues](https://cloud.githubusercontent.com/assets/7947294/7072216/9600f4b0-deb8-11e4-8772-709fe76b8d3a.png)

**Comment by Flyer53** [comment]
**Cursor:** Default modal or extended modal?
For the default modal the cursor css is set to *.css("cursor", "default")*. For extended modal no change is made by default, so it's a move cursor because the footer toolbar is an handle for draging. Are you using a Mac? If yes, is the hand the default cursor?

**Resize handle:** That's strange. It's the correct icon for the lower right resizer, but it's obviously not positioned correctly. Might be something with jQuery-UI. You have to load jsPanel css after jQuery-UI css, don't think that's the reason though ... Wrong only when using a modal?

**Comment by Flyer53** [comment]
**Cursor** Using a default modal there shouldn't be a resizer at all???

**Comment by genachka** [comment]
Sorry, my mistake, resizer should be there because I'm using paneltype modal extended. Not on a Mac, on Linux and the hand is not the default cursor. I'm yes, jsPanel is loaded after jQuery-UI.

**Comment by Flyer53** [comment]
Ok, on a extended modal the cursor is a move cursor as described above. So you have to change it with a callback to the one you want.
Leaves the resizer position .... but I currently have no idea ...

**Comment by genachka** [comment]
Adding float:right to .ui-resizable-handle.ui-resizable-se.ui-icon.ui-icon-gripsmall-diagonal-se puts it in the correct position.

Cursor, understood. I guess I never paid attention to it before, playing with it now seems odd as I don't typically expect to drag a window by the footer. I suppose if it really bothers the users I'll take advantage of the callback change option. ;)

**Comment by Flyer53** [comment]
Well, the necessary correction of resizer positioning somehow eludes me.
Positioning is done by jquery-ui and I only apply a small correction of css
bottom and text-indent. No need to understand everything, is there?

My thought behind making the footer also a drag handle is that it can
happen to accidentally get the header out of view or behind another
element. So if present a footer gives you still a chance to drag the panel.
Am 14.04.2015 18:56 schrieb "genachka" <notifications@github.com>:

**Comment by genachka** [comment]
@Flyer53 
I'm back to the drag handle. :) I've been playing with the tooltips, and noticed they too have drag handle shown on top and bottom even though those can never be moved. Seems odd to me. Maybe it's worth revisiting how that's done. If there's no option to drag, I think it shouldn't be showing an cursor that allows to drag.

**Comment by Flyer53** [comment]
@genachka 
You're fully correct, I just didn't pay attention to this a lot. I'm about to release a version 2.5.3 anyhow within the next days where this is corrected. So far 2.5.3 will have the following changes:
+ toolbars now get the same font-family as the title (changes in .addToolbar(), option.toolbarHeader and option.toolbarFooter)
+ css/styling for hints changed
+ jsPanel.hideControls() modified
+ almost all 'px' removed
+ option.load: inside the complete callback 'this' refers to the content property of the panel
+ option.ajax: inside the callback functions 'this' refers to the content property of the panel
+ option.ajax: new parameter 'autoload' (if set to 'false' returned data is NOT appended to content section by default)
+ option.callback: inside the callback functions 'this' refers to the jsPanel
+ setting size simplified internally and jsPanel.setSize() removed
+ Tooltips don't have a drag cursor anymore

Most of this are internal chnages/improvements, but the changes concerning option.ajax, option.load and option.callback might be useful.

**Comment by Flyer53** [comment]
@genachka 
Just uploaded the update to version 2.5.3 ....
