### ISSUE TITLE
Prevent dragging off page?

### ISSUE THREAD

**Issue by Jakobud** [Flyer53/jsPanel#31]
If you grab a panel and drag it, it is possible to drag it off the side of the page so that the page scrolls to following it, even if you have overflow-x hidden. Can you prevent the panels from being dragged off the page?

**Comment by Flyer53** [comment]
Use **option.draggable** with *containment* set to "window"
```javascript
$.jsPanel({
    draggable: {
        containment: "window"
    }
});
```
For more details see http://api.jqueryui.com/draggable/#option-containment
