### ISSUE TITLE
Cancel window closing

### ISSUE THREAD

**Issue by ivangfr** [Flyer53/jsPanel#32]
Hi,

In the jspanelbeforeclose event, is it possible to cancel the closing of the jsPanel after clicking on the close button?
I want to show a dialog if the user wants to really close the window. If not, the closing must be cancelled.

Thanks

**Comment by Flyer53** [comment]
Hi there, 
Currently this is not implemented, sorry. But I think it's a good idea and I will look into this. Just give me some time please...

**Comment by Flyer53** [comment]
Hi again,
I added the parameter **confirmClose** to **option.controls** in a version 2.5.0 Beta. You can use this parameter to enable a "close confirmation" for an individual panel like:
```javascript
$.jsPanel({
    controls: {
        confirmClose: "Do you really want to close the panel?"
    }
});
```
By default this parameter is set to **false**. If you set a text value this text is used for a modal dialog to confirm the close action. Download for testing http://jspanel.de/downloads/jsPanel-2.5.0Beta.zip
and give me some feedback please ...

**Comment by ivangfr** [comment]
Hi,

Thanks for the reply and for adding this new functionality.
I tried the new version on my application and it works.

However, I would suggest:
1) The dialog should be customazible. In fact I was thinking about using another jsPanel (centralized and with modal) to show the dialog.
2) I should have access to controls.confirmClose property because it can be false or true (with question text) depending on, in my case, if the user modified or not the document that is in the content of the jsPanel (like any text editor).

Thanks!

**Comment by Flyer53** [comment]
Your point 2)
You do have access to **controls.confirmClose**. Just create a panel and assign it to a variable. Then access the complete options object via **[variable]option**
```javascript
// create panel and assign it to variable
var myPanel = $.jsPanel();
// access and change confirmClose to activate close confirmation if needed
myPanel.option.controls.confirmClose = "text for the dialog ...";
// or deactivate again
myPanel.option.controls.confirmClose = false;
```
Your point 1)
I hear you. I have something in minde that possibly works without having to change the jsPanel script. Will do some tests and then I'll call you back here

**Comment by Flyer53** [comment]
Ok, I have a solution for your point 1) that does without a modification of the jsPanel script. The basic idea behind it is that you remove the standard close handler from the close button of your initial panel, assign a new handler to the close button that opens a modal jsPanel to ask the user for some action and is closed together or without the initial panel depending on what the user decides. Here is the example code:
```javascript
//step 1 - create a jsPanel and assign it to a variable
var myPanel = $.jsPanel({
	position: "center",
	theme: "medium"
});

//step 2 - remove the standard handler from the close button
$(".jsPanel-btn-close", myPanel).off();

//step 3
//first prepare a footer toolbar for the modal dialog(jsPanel)
//of course you could include the buttons in the panel content
var arr = [
	{
		item: '<button type="button"><span></span></button>',
		event: 'click',
		btntext: ' No',
		// closes only modal dialog
		callback: function (event) {event.data.close(); }
	},
	{
		item: '<button type="button"><span></span></button>',
		event: 'click',
		btntext: ' Yes',
		// closes both, modal dialog and initial jsPanel
		callback: function (event) {event.data.close(); jsPanel.close(myPanel); }
	}
];
//then assign new handler to close button of initial jsPanel
//that opens a new modal jsPanel to ask for user action (close or no close)
$(".jsPanel-btn-close", myPanel).click(function(){
	var check = $.jsPanel({
		paneltype : {
			type: 'modal',
			mode: 'extended'
		},
		position: "center",
		size: {width: 300, height: "auto"},
		removeHeader: true,
		toolbarFooter: arr,
		content: "<p style='text-align:center;padding:20px;'>Do you really want to close the panel?</p>"
	});
});

//step 4 (if needed) - restore original close handler
$(".jsPanel-btn-close", myPanel).click(function(){
	jsPanel.close(myPanel);
});
```

**Comment by ivangfr** [comment]
I didn't have time to implement this new approach that you suggested.
But I will do it as soon as possible and then I give you some feedback!
Thanks!

**Comment by ivangfr** [comment]
Hi there,

It worked perfctly and I am still using the version 2.4.1.
One question: is it possible to customize the modal overlay? Por example, change the color and/or opacity without modifying the .js?

Thanks

**Comment by Flyer53** [comment]
Sure, just add the necessary CSS to your application css file you load after jquery.jspanel.css. The following css is the default for background color and opacity you can adjust to the values you like.
```css
.jsPanel-backdrop{
    background: rgba( 0, 0, 0, 0.8 );
}
```

**Comment by ivangfr** [comment]
Hi, it would be amazing if when creating a jspanel we could provide the background color and opacity on options.paneltype for example. what do you think? Regards.

**Comment by Flyer53** [comment]
Hi Ivan
I don't really think this is necessary. If you want a different modal backdrop background color/opacity for all your modals it would really be better to change the css accordingly.
And if you want individual background color/opacity for various modal jsPanels just set the necessary css via the callback like:
```javascript
$.jsPanel({
  paneltype: "modal",
  theme:     "autumnbrown",
  callback: function () {
    $(".jsPanel-backdrop").css("background", "rgba(233,206,135,0.5)");
  }
});
```
It would be some more to change in the jsPanel script and I can't see a really good reason to add this extra code since you can achieve the same thing quite easily as described above. For you it's not more work than setting a configuration option ...

**Comment by ivangfr** [comment]
Hi, you are right!  I can implement as you suggested, using the callback function. Thanks!
