### ISSUE TITLE
Position in internet Explorer 11

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel#34]
Hello Stefen
1)  When I check the samples pages
     api / examples in ie11 (not happen in firefox).
    Example you can find in page
   http://jspanel.de/api/option/controls
    The result of the Position of jspanel is in the end of the page.
2)  Would you please Surround all console.Write with try-catch,
     Quite a few users ie working in mode called compatibility Mode to ie7/8
    I am receiving an error when the Page is loading the script jspanel

**Comment by Flyer53** [comment]
Hi Avi,
thanks for reporting this. Since I don't use IE I didn't notice this issue yet. Seems to happen only when using shortcuts like "center", "auto" and so on for option.position. Numbers and pixel values seem to work fine. I have yet to find out what's causing this

What is the error message you get? Could you please post it. And can you say which jsPanel version worked ok with IE?

A note on IE7/8: I do not support the older versions of IE.

**Comment by Flyer53** [comment]
Well Avi, I guess I found the error: I recently replacedthe  jquery methods **$(window).scrollTop()** with **window.scrollY** and missed that IE doesn't provide **window.scrollY**. Same is true for **$(window).scrollLeft()** and **window.scrollX**.

I replaced all occurances of *window.scrollY* and *window.scrollX* with the jquery methods again and it seems to work now on IE again. I'll make some more tests and when it works out ok I'll release a fixed version tomorrow.

Sorry for the inconvenience, Stefan

**Comment by Flyer53** [comment]
Released version 2.5.2.
Think it's fixed, feedback welcome :)

**Comment by AviHafner** [comment]
Hi Stefan
You can see how to config  the ie11 browser to work in in ie7 computable mode
In the link https://support.microsoft.com/en-us/kb/2536204/
I don’t need jspanel to work in compatible mode , in my script I recognize this kind of situation and avoid using jspanel ,

But I am using in my script code to avoid the loading of jspanel not to get the messages
Error messages:
Line: 2
Error: 'console' is undefined

Yours
Hafner Avi



Hafner Avi
        •    (w): 972-4-829-5728
        • hafner@technion.ac.il<mailto:hafner@tx.technion.ac.il>

**Comment by Flyer53** [comment]
Hi Avi,

so when I understand you correctly the issue itself (positioning of the panels in IE) is fixed.

**console** is not a JavaScript feature but specific to the used JavaSript engine. So when the engine doesn't offer the method **console** you get an error message. Do you think I should use **alert** instead? That would work in all browsers.

Best regards, Stefan

**Comment by AviHafner** [comment]
Thanks Stephen
It works properly



Hafner Avi
        •    (w): 972-4-829-5728
        • hafner@technion.ac.il<mailto:hafner@tx.technion.ac.il>
