### ISSUE TITLE
Resize Handle being displayed on bottom left

### ISSUE THREAD

**Issue by areel** [Flyer53/jsPanel#35]
Hi

Using version 2.5.2, totally clean project folder, only jspanel installed via bower, using webstorm to serve index.html.
``` html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="bower_components/jspanel/source/jquery.jspanel.css" />
</head>
<body>
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="bower_components/jquery-ui/jquery-ui.js"></script>
<script src="bower_components/jspanel/source/jquery.jspanel.js"></script>
<script>
    $.jsPanel();
</script>
</body>
</html>
```
The resize handle appears in the bottom left corner, can initate resize anywhere in footer for first resize, after first resize is completed the footer is no longer renendered and resizing not active.

This occurs in latest versions of IE, Chrome and Firefox.

Attached some screenshots from Firefox.

![jspanelscreenshots](https://cloud.githubusercontent.com/assets/573567/7670398/c14853c0-fc9a-11e4-867a-36cdb825ec4d.png)

Regards

Aidan

**Comment by Flyer53** [comment]
Hi Aidan,
The jQuery UI css file is missing. That should do it. In the jsPanel css file I included only the style declarations that are different from the original jQuery UI css.

I'm already thinking about including the necessary jQuery UI css in the jsPanel css file. Might come with the next update.

Regards, Stefan

**Comment by areel** [comment]
Correct. I added the missing reference to one of jquery-ui's css files and the issue was resolved.

Regarding including the necessary files etc. From my use case, I am considering including your component into an angular/bootstrap/jquery codebase that has (until now) no dependency on jquery-ui. I would find it preferable if your component was self contained especially since jquery-ui doesn't work seamlessly with wiredep (e.g doesn't pull in css).

Thanks for the prompt response.

**Comment by Flyer53** [comment]
Your welcome,
I totally agree with you concerning dependencies and would gladly do without jquery ui. But I have to admit here that I'm not what you would call a professional programmer. So I might try to get rid of jquery ui one day but can't promise when or whether at all this will happen.

**Comment by areel** [comment]
Hi

 

I didn’t mean not to use jquery-ui, I read your comment to mean that you were considering having the subset of jqueryui components you use (a custom build) wrapped within your component.

I was saying that would be my preference since it would mean that my codebase size would only be what was needed.

At the moment I am pulling in all jquery-ui and having to handle the jquery-ui css import separately from the rest of my gulp/wiredep code because jquery-ui doesn’t (yet) work seamlessly with bower/wiredep.

So my vote would be for wrapping, as it would make my dependency life easier but others who make fuller use of jquery-ui via bower will probably not want such an approach because of carrying more than one version (somewhat like npm).

 

Regards

 

Aidan

**Comment by Flyer53** [comment]
Ok, now I understand you.

So it might make sense to branch out a version that includes all necessary jquery-ui js/css in the respective jsPanel files. Let me think about this ...

Take care, Stefan
