### ISSUE TITLE
wrong behavior of jspanel tooltip 

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel#40]
Hello Stefan
When I use a tooltip of jspanel that point to element that has href, the href becomes inactive?

I am sending you two examples
1) jspanel tooltip that the href is behave wrong behavior -href is  inactive:
 http://www.admin.technion.ac.il/avi/Jspanel.html
2) Qtip2 that behave with normal functions : http://www.admin.technion.ac.il/avi/qtip2.html

Your
Hafner Avi

**Comment by AviHafner** [comment]
Hello  Stefan
I apologize
This incorrect behavior is characteristic only for jspanel tooltip in browsers from Microsoft
ie11 and edge (windows10 browser).
Hafner Avi

**Comment by Flyer53** [comment]
Hi Avi,
thanks for the report :) Well, have to admit that I didn't do any testing yet with Windows 10 at all.

But I also noticed that you did not load jquery UI in your example 1). Would you mind trying how it works out when jquery UI is loaded?

Regards, Stefan

**Comment by AviHafner** [comment]
Hi Stefan
http://www.admin.technion.ac.il/avi/Jspanel.html
I add to the example the jquery UI
And I am getting the same result

I am using qtip2 to solve this problem in internet explorer

Hafner Avi
        •    (w): 972-4-829-5728
        • hafner@technion.ac.il<mailto:hafner@tx.technion.ac.il>

**Comment by Flyer53** [comment]
Thanks again for the quick response Avi. I'll see what I can find out ...

Take care, Stefan

**Comment by Flyer53** [comment]
Ok Avi, found a workaround that works on IE11 on my Windows 8.1 machine:

Leave the href attribute blank
```html
<a id="setup" href="#">Tooltip JsPanel</a>
```
and add a click handler additionally to the mouseover
```javascript
$('#setup').mouseenter(function () {
        $.jsPanel({
                // tooltip
        });
});

$('#setup').click(function (e) {
        e.preventDefault();
        location.href = "http://jspanel.de/";
});
```

**Comment by AviHafner** [comment]
I apologize Stephen
It does not work   : http://www.admin.technion.ac.il/avi/Jspanel.html
I tried the suggestion with IE11 on Windows 10
And several other operating systems such as
windows 2008R2 and windows 2012R2

Yours
Hafner Avi
        •    (w): 972-4-829-5728
        • hafner@technion.ac.il<mailto:hafner@tx.technion.ac.il>

**Comment by Flyer53** [comment]
Not your fault Avi! That's something I have to take care of and I'll try to find out why this doesn't work with IE on Windows 10. But I'll wait for the official release of Windows 10 by the end of July. Maybe something happens until then ...

Take care, Stefan :)

**Comment by AviHafner** [comment]
#### Hello Stefan
Do you have an evaluation when a failure that  happening in internet-Explorer  And edge With jsPanel version 2.5.? Will be solved.
Please Check the links
http://www.admin.technion.ac.il/avi/Jspanel.html
http://www.admin.technion.ac.il/avi/qtip2.html

#### in version 3.0
in each Options that change in version 3.0 Can you add documentation what's is the change that happened in version 3.0, which had in this Options.

#### Looking forward to version 3.0 
Yours 
Hafner

**Comment by Flyer53** [comment]
@AviHafner 
Hi Avi,
Checked your examples and have to admit that I have no idea what causes this behaviour in IE. One guess is that it might have to do with the ugly wrapper object I use. 

But at least I found out that it seems to be something specific to the <code>a</code> element. If I, for example, replace the anchor element with a <code>button</code> or <code>span</code> it works just fine on my machine with IE11 and Windows 8.1.
So if that's a possibility for you I recommend replacing the anchor element with something else.

**jsPanel 3** at the moment is still strictly experimental, subject to a lot of changes and the Alpha on the current beta page is already out of date. As soon as I have something new ready to show I'll also update some documentation. Some key points:
+ completely new positioning function (take a look at http://stefanstraesser.eu/projekte/jsUtilities/)
+ remove dependency on jQuery-UI
+ more native JavaScript - less jQuery
+ tooltips without the need of this ugly wrapper around trigger and tooltip
+ remove the need to move minimized jsPanels to another container
+ improved event implementation

Regards, Stefan

**Comment by Flyer53** [comment]
Hi Avi,
though I didn't investigate this issue any further in the 2.5.x version I did not forget it.
And as far as I tested this seems not to be an issue anymore with jsPanel 3 :)
Regards, Stefan

**Comment by Flyer53** [comment]
@AviHafner 
Hi Avi,
Well, I don't seem to be able to fix this issue in the jsPanel 2.x version. I'm quite sure it has to do with jquery.wrap() I use in version 2.x. But I did not find a fix.

At least my tests with jsPanel 3 don't show this problem. In jsPanel 3 I don't need this uggly wrapper object anymore (a lot better).

If you don't mind I would close this isue.

Regards, Stefan
