### ISSUE TITLE
jsPanel() function opens 2 files

### ISSUE THREAD

**Issue by Mick89** [Flyer53/jsPanel#45]
Hello,

There seems to be a bug with version 2.5.3.

The $.jsPanel(); function opens 2 files.
For example, example loading table data on your homepage, opens with a click on button Go : 

Get : http://jspanel.de/files/summits.html 200 OK 169ms
Get : http://jspanel.de/index.html 200 OK 61ms

The request on the /index.html page is normally useless?

I have the same problem on my pages.
A possible solution?

I do not have this problem with the previous version 2.5.2.

Thanks again!
Mick

**Comment by Flyer53** [comment]
@Mick89 
Hi Mick, thanks for reporting this :)
It seems to be something specific to **option.load** I have yet to investigate.

As far as I can say atm it does not happen when using **option.ajax**

So instead of
```javascript
$.jsPanel({
    load: {
        url: "url",
        complete: function(){}
    }
});
```
use
```javascript
$.jsPanel({
    ajax: {
        url: "url",
        done: function(){}
    }
});
```
and it should be ok

Regards, Stefan

**Comment by Flyer53** [comment]
@Mick89 
Well, I might be blind to the obvious, but I can't find the error behind this issue. I'm sorry!

So I suggest you just move to using option.ajax. Gives you more options anyhow ...

Stefan

**Comment by Flyer53** [comment]
Since the coming version 3 of jsPanel won't have option.load anymore I won't investigate this any further.
jsPanel 3 is coming along nicely and short of Beta status.
Preview available here: http://beta.jspanel.de/
