### ISSUE TITLE
Unwanted http request each time $jsPanel() is called

### ISSUE THREAD

**Issue by serfer2** [Flyer53/jsPanel#48]
Hi,

I paid attention to a curious thing: each time $.jsPanel() is called, it fires an HTTP Request to the server. Like an Ajax call. Doesn't matter which options you use.

It happens also in http://jspanel.de/ examples. If you open firebug and see the console, you'll see HTTP Request/Response trace like:  "XHR Loaded (jspanel.de - 200 OK ..."

I'm using it in a project and I'm getting "no sense" HTTP Requests each time jsPanel is called.

Is it normal? Is it necessary?

Regards ;-)

**Comment by Flyer53** [comment]
@serfer2 
Thanks for reporting ... and no, it's not normal or intended and absolutely not necessary. I'll see what I can find...

BTW: jsPanel 3 Alpha doesn't show this behaviour ... in case you want to take a look:
http://beta.jspanel.de/index.html

**Comment by Flyer53** [comment]
Ok, I found the error :)

Give me a day to publish a fixed release please ...

**Comment by Flyer53** [comment]
**Version 2.5.5 with the fix is released :)**

Thanks again for reporting ...

**Comment by serfer2** [comment]
Thanks to you for your great work ;-)
