### ISSUE TITLE
How to automatically minimize the panel if focus is lost?

### ISSUE THREAD

**Issue by thecenz1** [Flyer53/jsPanel#53]
Hi, I try to automatically minimize the panel when user clicks out of it. I have tried the following but it doesn't work :

var this_panel = $.jsPanel({
...
...
    callback: function(){
				// minimize the panel if focus is lost
				$(document).on('blur', this_panel, function () {
					this_panel.minimize();
				});

**Comment by Flyer53** [comment]
Hi there,
your code can't work because you bind a blur event handler to the document. But the document is what you click on every time you click something. And the jsPanel doesn't dispatch a blur event when loosing focus. So we have to find another way.

I'll try to find something for you after the Christmas hollidays, ok!? So be patient please and ...

Merry Christmas :)

**Comment by thecenz1** [comment]
Thanks for the answer. Yeah I see that the jsPanel doesn't return a blur event when loosing focus. No hurry man^^

Merry christmas to you too!

**Comment by Flyer53** [comment]
Hi again,
now I might have a solution that hopefully works for you. But it has 2 requirements:
1. Append the jsPanel in question to the body element (don't use option.selector)
2. Put your page content not directly in the body element but in a dedicated container like (just an example):
```html
<html><head></head>
<body>
    <div class="container">
        <!-- your page content goes here -->
    </div>
</body></html>
```
... and then:
```javascript
$.jsPanel({
    // panel config without option.selector
    callback: function(panel) {
        $(document).on('click', '.container', function() {
            panel.minimize();
        });
    }
});
```
This would be the easiest way to make your issue work. The important part is that your jsPanel is not appended to a container which is a descendant of the element you click to minimize the panel.

Let me know whether this works for you ...

**Comment by thecenz1** [comment]
Well, my website was already with a main container and the panel attached to the document. So it is a perfect solution for me. Thanks a lot
