### ISSUE TITLE
Set default offset with error

### ISSUE THREAD

**Issue by leandroluk** [Flyer53/jsPanel#54]
Hello,

Congratulations for the plugin, I use it and it works great ... Today I found an error in the ability to set the default panel starting position. when use the config:

    $.jsPanel.defaults.overlay.top = '60px';
    $.jsPanel.defaults.overlay.left = '60px';

the panels do not start from that config... also tried telling integer values but nothing right.

    $.jsPanel.defaults.overlay.top = 60;
    $.jsPanel.defaults.overlay.left = 60;

sorry my english, Google Translate helped me rs

**Comment by leandroluk** [comment]
WOW! I managed to get the fix. The plugin documentation is wrong. She says to modify the default position should use the parameter **offset** but actually have to use the parameter **position**

**Comment by Flyer53** [comment]
Hi there and thanks :))
I just tried what you reported and it works as intended. Could it be that you had a spelling error in your code?
Your posting above reads
```javascript
$.jsPanel.defaults.overlay.top = '60px';
```
... and there is no option **overlay** !!

With
```javascript
$.jsPanel.defaults.offset.top = '60px';
```
I don't see any errors. Could you please check and give me a note. Thanks

**Comment by leandroluk** [comment]
really use the offset does not. in my code block of m using the following:

    $.jsPanel.defaults.position = {top:60,left:60};

if you work with the **overlay** does not work

**Comment by Flyer53** [comment]
Don't mix up 2 things here. **option.position.top** is not the same as **option.offset.top** and in your statement above you again talk about **overlay**. But **there is no such thing as an *option.overlay* and therefore using *overlay* in whatever way does not have any effect.**

**option.offset.top** is an additional pixel value added to whatever is calculated for css top. Example:
```javascript
$.jsPanel({
    position: "top left", // positions the panel at the top left corner
    offset: { top: 50, left: 50 } // moves the panel right and down by 50 pixels
});
// is the same as
$.jsPanel({
    position:  { top: 50, left: 50 }
});
```
Take a look at http://jspanel.de/api/option/offset to get a better idea of **option.offset** and what it's good for.

And once again: **An *option.overlay* does NOT exsist!**
