### ISSUE TITLE
jsPanel 3.0.0 Beta

### ISSUE THREAD

**Issue by Flyer53** [Flyer53/jsPanel#55]
**jsPanel 3.0.0 is now in beta status.
So I won't make any more changes to the API.**
To each item on the API pages I added a short info concerning **migration from 2.x to 3.0.0.**
To anyone who bothers to take a look ... I really would appreciate some feedback.
jsPanel 3 Beta also seems to work fine with **jQuery 3.0.0 Beta 1**
http://beta.jspanel.de/

**Comment by AviHafner** [comment]
Hello **Stefan**
Congratulations
I'm waiting to try the innovations in the new version, 
I apologize for my late response.
Stefan I have a few questions for you.

1)  Is the JsPanel 3 version supports jQuery Version 3,
Another great product that I use it is [tablesorter](http://mottie.github.io/tablesorter/docs/),

Their Developers have stated [in one of the versions of the product](https://github.com/Mottie/tablesorter/wiki/Changes#version-2252-1152016) that is up to date and ready to work with jQuery version 3

2)  How ready and stable is  beta version, I can try it on a real project,
In the case when all is Working ,
 can I  Move it to production environment

Thanks and good day
yours 
Hafner Avi

**Comment by Flyer53** [comment]
Hi Avi, thanks a lot ... and don't worry, everything's fine :)

Your questions:
**1)** My first tests with jQuery 3 work fine, but I have yet to test every single jsPanel feature together with jQuery 3. And since jQuery 3 itself just turned Beta I don't know whether there will be any changes to jQuery 3 affecting jsPanel.
I have one project using tablesorter as well and I'll check that with jQuery 3
**2)** I think jsPanel 3 Beta is stable. At least I didn't have any problems in my tests and the few projects where I use it. **I won't make changes anymore to the API.** So changes that might come will not affect the current features. And I currently don't plan to add something new ... or is there something you would like to see in jsPanel?

I didn't have that much time lately to take care of jsPanel. But I intend to check out jsPanel 3 together with jQuery 3 next week ...

Hope I could give you some answers ..

My best regards, Stefan

**Comment by Flyer53** [comment]
@AviHafner 
Hey Avi, just made a quick check in one of my projects using:
+ **jQuery 3 Beta 1**
+ jQuery-UI 1.11.4
+ **jsPanel 3 Beta**
+ **tablesorter 2.14.5** (current version is 2.25.3)
+ jquery.contextMenu 2.1.0
+ CKEditor 4.3.1

... looks :+1: 

But realized that Boorstrap 3.x does not work with jQuery 3 Beta

**Comment by AviHafner** [comment]
Hey **Stefan**
Unfortunately I did not implement the bootstrap in my projects,
**JQuery 3** -  i Implement in my projects when it will not be a beta,
I'll check and implement **JsPanel 3** Next week .

Thank you 
and Good Day

**Comment by thecenz1** [comment]
Hey :)
Just installed it and I would suggest that on your doc you make an explicit note on the main page about  including the jspanel files to your html. I got confused by the jquery.jspanel-compiled.js :)
Everything works smoothly, tinyMCE does not have anymore focus issues.
I just have some css issues compared to v2.x. For ex on the content, options of a <select> are all displayed on the same line.
Also have problems with float properties in the footer, but have not yet checked what it comes from. I'll come back to you later.

**Comment by Flyer53** [comment]
Hi again :)
Yes, you're correct, I have to make a note concerning the two js files. You should use **jquery.jspanel-compiled.js** because this is the one where ES6 features are compiled to ES5. I guess the Chrome error message will disappear then.

Your problems with float properties in the footer: As of jsPanel 3 he footer toolbar container (.jsPanel-ftr) uses css **display: flex** by default (I have to make a note on this in the docs as well). So there is no need for floats. And depending on your needs the items in the footer should then be flex items.

The problem with option selects is new to me and I can't say something useful about this at the moment....

Keep testing ;) and thanks for your feedback :+1:

**Comment by thecenz1** [comment]
Yes the chrome error disappear when I remove jquery.jspanel.js and attach only the compiled file.

Oh ok for the flex display. Just one thing doesn't sound very logical to me, why have you chosen flex-direction as row-reverse ? It would be logical that the flex-item get displayed in the order they have been coded.

**Comment by Flyer53** [comment]
@thecenz1 
Footer flex-direction: row-reverse
Well, I simply want any footer toolbar items - which I think will be buttons in most cases - right aligned by default. But if that does not meet your needs you can easily override the css.

**Comment by Flyer53** [comment]
Just updated the beta documentation a bit and added a few **migration infos** to the jsPanel Beta homepage http://beta.jspanel.de

**Comment by Flyer53** [comment]
The Beta got a little update where I corrected a few minor issues with the CSS when using **option.headerRemove**
http://beta.jspanel.de/api/

**Comment by Flyer53** [comment]
Just uploaded jsPanel 3 Beta 1.2
+ **option.theme** improved (no need to remove whitespace from color values anymore)
+ **Removed the HTMLElement.dataset polyfill** -> IE10 is not supported anymore by jsPanel 3 since Microsoft stopped support for IE10 in January

**Comment by gbaumgart** [comment]
Hi, where can I download Beta 1.2 ? I found it always confusing to get those betas ;-). And, does that beta has support for bootstrap yet? Doesn't look like. Thank you!

**Comment by Flyer53** [comment]
@gbaumgart 
http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip

The bootstrap support is there. There's just no **option.bootstrap** anymore. It's implemented now within **option.theme** like:
```javascript
$.jsPanel({
    theme: 'bootstrap-primary'
});
```
Should even work with Bootstrap 4, but since Bootstrap 4 itself is still an alpha version I wouldn't rely on that too much.

**Comment by gbaumgart** [comment]
thats fine with me. thanks for the response!

**Comment by Flyer53** [comment]
Made a slight modification to the method **.reposition(arg)**
If used without **arg** it defaults to the current value of **option.position**
Take a look at http://beta.jspanel.de/api/#method/reposition Example 3 to see it in action.

Further I went over the API docs, corrected a few issues there and added the one or the other better example.

Download the modified Beta http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip

**Comment by thecenz1** [comment]
Hey :) still testing and I have to admit the v3 works really great and looks really neat!
Got a little issue with content. If I set a div with height 100%, and I set a footer, then when I inspect my content div, its height includes the footer. If I remember well it wasn't like that in v2.

**Comment by Flyer53** [comment]
@thecenz1 
That's nice to hear ... thank you very much :)

I'm not sure wether I understand your content issue. I tried to reproduce this by taking an panel with footer toolbar, adding a div (with height set to 100%) to the content section. Works fine, no issue! So maybe that's not what you mean. Could you please explain this some more ...  or post some sample code?

**Comment by Flyer53** [comment]
@thecenz1 
Tried something and I have an idea what you might mean.
Could it be that your content section is something like the code example below?
```html
<div class="jsPanel-content">
    <div style="height:100%">some content</div>
    <div style="position:absolute;bottom:0;widht:100%;height40px;">your footer</div>
</div>
```
If so, the behaviour you described is fully normal because the footer div is taken out of the normal flow of elements due to the positioning. And then the first div extends fully down to the bottom.

In this case you could set ccs height for the first div like:
```html
<div style="height:calc(100% - 40px);">some content</div>
```

**Comment by thecenz1** [comment]
Here's my content builder : 

function build_jsPanel_document_body() {
```
	var popup_document = "				<div style='height:100%; width:100%;'>"; 
	popup_document = popup_document + "		<div class='new_document_td_models_list'><div id='dl-menu' class='dl-menuwrapper'><button class='dl-trigger'>Utiliser un modèle</button><img class='new_document_image' src='./img/clickhere.png' alt='Sélectionnez un modèle' height='35px'/></div></div>"; 
    popup_document = popup_document + "		<table id='new_document_nav_container'>"; 
	popup_document = popup_document + "			<tr id='new_document_text_body' class='new_document_div' valign='middle'>"; // document text
	popup_document = popup_document + "				<td id='document_text_td' valign='middle'><form id='new_document_form' method='post'><textarea id='new_document_body'></textarea></form></td>";
	popup_document = popup_document + "			</tr>";
	popup_document = popup_document + "		</table>";
	popup_document = popup_document + "	</div>";
	return popup_document;
}
```

As you can see it is set to use 100% width and height.... once my jsPanel is instanciated, I inspect the code in chrome, and when I select my main div, the blue frame that chrome displays to show the container is including the footer....
I have set scroll to auto so that could be the overflow, but then how could there be overflow if my div is 100%....

**Comment by Flyer53** [comment]
@thecenz1 
May I first suggest that you rewrite this function. You don't need to repeat *popup_document = popup_document +* all the time:
```javascript
function build_jsPanel_document_body() {
    var popup_document ="<div style='height:100%; width:100%;'>"+ 
	"<div class='new_document_td_models_list'>"+
		"<div id='dl-menu' class='dl-menuwrapper'>"+
			"<button class='dl-trigger'>Utiliser un modèle</button>"+
			"<img class='new_document_image' src='./img/clickhere.png' alt='Sélectionnez un modèle' height='35px'>"+
		"</div>"+
	"</div>"+
	"<table id='new_document_nav_container'>"+
		"<tr id='new_document_text_body' class='new_document_div' valign='middle'>"+ // document text
			"<td id='document_text_td' valign='middle'><form id='new_document_form' method='post'><textarea id='new_document_body'></textarea></form></td>"+
		"</tr>"+
	"</table>"+
"</div>"
    return popup_document;
}
```
Then a few questions:
+ There must must be some more CSS applied to your HTML code. Without knowing this CSS I can't answer your issue
+ What actually is the footer you're talking about? Your supplied HTML has only one outer DIV whose height is 100% including a few childelements. But there is nothing outside the 100% height DIV that you would expect not to be enclosed by the 100% height DIV

**Would you mind moving this issue to email? info@jspanel.de**
This really doesn't seem to be a jsPanel issue.

**Comment by thecenz1** [comment]
Yeah you're right, I've coded a fresh panel example and I can't reproduce the issue. I have deleted my earlier messages so it doesn't fill the thread with not related issues. I'll figure out the issue, but thanks for your help

**Comment by Flyer53** [comment]
@thecenz1 
Don't worry ... welcome any time ... :)

**Comment by Flyer53** [comment]
Just **uploaded Beta 1.3** with a little change in **option.contentAjax**
Inside the callback functions **done(), fail(), always()** and **then()** the <code>this</code> keyword now refers to the **jsPanel** and not to the content section as before.
I made this change in order to have the value the <code>this</code> keyword refers to more consistent acrooss the whole project. Now it's the same for option.contentAjax and option.callback

http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip

**Comment by Flyer53** [comment]
Once again the Beta got an update:
+ the **tooltip** feature had a few bugs I corrected
+ **option.contentSize** now alternately accepts a string to pass width and height values seperated by a space like <code>"500 350"</code> or <code>"500px 350px"</code> as alternative to <code>{ width: 500, height: 350}</code>
+ sanitized the code and moved some more code to functions
+ went over all the api docs, corrected a few errors and made everything a bit more understandable I hope ;)

http://beta.jspanel.de/
http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip

**Comment by Flyer53** [comment]
Two more small issues with tooltips solved
+ flickering tooltip solved. Happened sometimes when mouse pointer was over the connector of the tooltip
+ tooltips should now work with all events that make sense (not only on mouseenter/mouseover)
+ js and css is updated this time

http://beta.jspanel.de/api/#option/paneltype
http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip

**Comment by Flyer53** [comment]
**New**
Added a simple way to add custom themes to jsPanel.
Take a look at http://beta.jspanel.de/#customthemes
Download latest Beta http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip

**Comment by thecenz1** [comment]
Hey, I'd like to cascade the panels with offsetX & offsetY. Typically I would multiply a value, let's say 10, by the panels array length or the panel nr.... is there such option somewhere, didn't find it in the doc ?

**Comment by Flyer53** [comment]
@thecenz1  Hi again,
there is no specific option just for this. But you can easily achieve this with:
```javascript
$.jsPanel({
  position: {
    my: 'left-top',
    at: 'left-top',
    modify: function(){
      var count = $('.jsPanel').length - 1;
      return {left: count * 30, top: count * 30};
    }
  }
});
```
or if you prefer to use offsetX and offsetY:
```javascript
$.jsPanel({
  position: {
    my: 'left-top',
    at: 'left-top',
    offsetX: function() {
	  var count = $('.jsPanel').length -1;
      return count * 30;
    },
    offsetY: function() {
      var count = $('.jsPanel').length -1;
      return count * 30;
    }
  }
});
```
These two example of course count all panels in the page. If you want to limit the count to certain panels I would add a specific class name to the panels you want to position like this.

**Comment by Flyer53** [comment]
**Request your opinion**
With the latest beta update I uploaded a few minutes ago I added a new feature for which I'd like to get some opinions:
So far the only way to call a method of an individual panel was to call the method on a reference you safed when creating a panel like:
```javascript
var mypanel = $.jsPanel();
mypanel.close();
```
But what if you don't have such a reference, for whatever reason?
The latest beta extends the outer div element of each individual panel (not the element prototype) with the property <code>jsPanel</code> and this prop stores some of the panel methods. So you just need to identify the panel somehow and then call the method on the element like:
```javascript
$.jsPanel({
    id: "mypanel-1"
});
document.getElementById("mypanel-1").jsPanel.close();
// or with jquery
$("#mypanel-1")[0].jsPanel.close();
```
For test purposes only the methods <code>close</code>, <code>minimize</code>, <code>maximize</code>, <code>normalize</code> and <code>smallify</code> can be called this way.
I know, some people say it's not a good idea to extend a native element. But how likely is it that some day an HTMLElement will have a native property named <code>jsPanel</code>? 

What do you think?

**Comment by thecenz1** [comment]
Hi, I think it's a good idea. I anyway always call my panels by their id, not by var reference.
One example I find usefull is to store the instances in an array. For example the wysiwig editor tinyMCE, when you have multiple editor instances, can be called this way:
tinymce.getEditor(x).method where x can be the editor id or the position in the editor array. This way the number of editors can be quickly reached tinymce.editors.length(), and treatments can be applied in sequences to all editors. I think it is a more convenient way than extending a native element, but that's only my opinion ;)

**Comment by genachka** [comment]
@Flyer53 
Many jquery plugins I use do it that way and I would support this approach.

**Comment by Flyer53** [comment]
@thecenz1 @genachka 
Thanks for the comments :)
@thecenz1 
It reads a bit like "Would be nice to have some built in tracking of active panels" ?

**Comment by genachka** [comment]
@Flyer53 
Hmm "active panel" tracking would be useful for me. ;)

**Comment by thecenz1** [comment]
I would find it very useful :) and @genachka is right, I use also a lot of plugins in that way too

**Comment by Flyer53** [comment]
@genachka @thecenz1 
Ok folks! Copied. I'll put this on the TODO list. But I don't promise this to be in the first release of version 3. More probably in a 3.1.

**Comment by Flyer53** [comment]
@genachka @thecenz1 
Now folks take a look at http://beta.jspanel.de/api/#method/resize 
Scroll all the way down to see the news :)

**Comment by thecenz1** [comment]
Wonderful!! Thanks for the great job!

I was thinking about it this afternoon ;) I also have a suggestion of feature for you:
the possibility to link panels between each other physically. Let me detail.... imagine you have 2 panels. The right edge of the first one is glued to the left edge of the second one. When you hover this glue line, the resize pointer displays. I you resize the first panel left (reducing its width), then it automatically resize the second panel . 
This glue effect would allow to make a multipanel dashboard where windows could be arranged but always using the same space.

**Comment by Flyer53** [comment]
@thecenz1 
That's a very interesting idea!
I made a little research and found a jquery plugin that more or less does exactly what you propose. Just added an example that opens a jsPanel with 2 divs and a seperator inbetween that behaves as you described.
Go to http://beta.jspanel.de/api/#option/contentAjax and scroll down to example 7. I think this is even better than having 2 jsPanels you have to "glue" together somehow. What do you think?

**Comment by thecenz1** [comment]
I've already seen such plugins  that's why the idea came, but somehow your panels "glued" would be more valuable. Imagine if you have several panel glued, that you could move them together, minimize them, etc.... that would allow possibility to display multiple dashboard in one window just by minimizing/maximizing....

**Comment by thecenz1** [comment]
Yes that's quite cool, have to think about that^^ but imo gluing panels would allow more flexibility in combination, and for ex minimizing of only one part of the dashboard.... but that's already a great tool as it is right now! Congrats that you keep it open sourced, most of the people would have put it on code canyon^^

**Comment by genachka** [comment]
Nice!

**Comment by Flyer53** [comment]
@thecenz1 @genachka 
Thanks :) ... Yep, it's open source .... and that's it!
@thecenz1 
Ok, I understand. Since you can nest jsPanels I'm asking myself whether this might be half the thing already. The code below opens an outer panel with 4 childpanels appended to the content section of the outer panel. The childpanel's draging is confined to the parent panel. You minimize the outer panel, the childpanels are sort of minimized as well. If I could add some code that makes selected panels responsive to changes in other panels ... that might do the trick???
```javascript
var outer = $.jsPanel({
	headerTitle: "outer Panel",
	theme: "rebeccapurple filled",
	contentSize: {
		width: function(){return $(window).width()-40},
		height: function(){return $(window).height()-81}
	}
});

var w = outer.content.width()/2-10;
var h = outer.content.height()/2-51;
var commonconfig = {
	container: outer.content,
	contentSize: { width: w, height: h },
	draggable: {containment: "parent"}
};

var innerLT = $.jsPanel({
	headerTitle: "inner panel left-top",
	position: "left-top 5 5",
	content: "<p style='padding:10px'>Draging of inner panels is confined to content section of outer panel.</p>",
	config: commonconfig
});

var innerRT = $.jsPanel({
	headerTitle: "inner panel right-top",
	position: "right-top -5 5",
	config: commonconfig
});

var innerLB = $.jsPanel({
	headerTitle: "inner panel left-bottom",
	position: "left-bottom 5 -5",
	config: commonconfig
});

var innerRB = $.jsPanel({
	headerTitle: "inner panel right-bottom",
	position: "right-bottom -5 -5",
	config: commonconfig
});
```

**Comment by Flyer53** [comment]
The next beta update is online.
I reworked the events in jsPanel and now use jQuery.trigger() to do the custom events ... less code and easier to handle. A handler for a jsPanel event now looks like:
```javascript
$(document).on("jspanelloaded", function (event, id) {
  // event is the event object
  // id is the id attribute value of the panel triggering the event
});
```

**Comment by Flyer53** [comment]
The next beta update is available.
+ fixed an issue with the **close()** method
+ added some documentation about the global object **jsPanel**

http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip
http://beta.jspanel.de/#windowjspanel

**Comment by Flyer53** [comment]
@thecenz1 
Just added an example to the api doc of option.resizable. Take a look at example 4. It combines 2 jsPanels ...
+ drag either one of the panels and the other panel drags with it
+ resize the left panel and
    + height of right panel is synchronized
    + width of right panel is increased/decreased to maintain overall width of both panels
+ close left panel and right panel closes as well
+ minimize/normalize left panel and right panel minimizes/normalizes as well

I think that already has quite a lot of your idea, and it's  done with the current code base
http://beta.jspanel.de/api/#option/resizable

**Comment by Flyer53** [comment]
**Next improvement:**
jsPanels that are appended to another jsPanel as childpanel will minimize to the lower left corner of the parent panel and not to the lower left corner of the viewport.

**Comment by thecenz1** [comment]
hey, easter weekend pushed me away from the internet ;)
Yes it is exactly what I was meaning. Just the link doesn't look very neat.... probably cause of the box shadow.
I would suggest that together with the example number you put a title to the example. For SEO purpose it would be great and people who are searching for something like that would find it more easily.
Also if you want a good example of panels usage, you can have a look at hootsuite. They have a free trial. I like a lot their UI and its flexibility. It can be good inspiration for you :)

**Comment by Flyer53** [comment]
@thecenz1 
Quite normal ... I had some spare time ;)
Your correct, it's the box shadow ... but for demo purposes ...
Just added example 5 that's quite similar but wraps those two panels in a parent panel. Resize the parent panel and the two "childpanels" resize as well on mouseup to fill the complete content section of the parent panel: http://beta.jspanel.de/api/#option/resizable
And thanks for the tip :)

**Comment by Flyer53** [comment]
**Beta update online**
http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip
+ **bugfix** fixed a bug causing problems with certain tooltip configurations
+ **updated beta documentation**
+ **option.headerControls** now allows to remove individual controls (not only disabling)

**Comment by Flyer53** [comment]
### jsPanel 3 is now a release candidate

http://beta.jspanel.de/downloads/jsPanel-3.0.0-RC1.zip

I don't want to make any more changes until releasing a first version 3, just bugfixes if something comes up.

One thing I'm not sure about yet: Should I create a new repo for version 3 or should I just go on with the current jsPanel repo? What do you think?

**Comment by Flyer53** [comment]
**jsPanel version 3 is now in its own repo!**
https://github.com/Flyer53/jsPanel3
