### ISSUE TITLE
sample/test files missing?

### ISSUE THREAD

**Issue by gbaumgart** [Flyer53/jsPanel#56]
Hi,
could you include please some boiler code files in your releases. It takes quite some time to pull everything together yourself, just to see something working.

thanks.
g

**Comment by Flyer53** [comment]
@gbaumgart 
Here you go: http://jspanel.de/downloads/example.zip
This is for jsPanel version 2.6.1
Let me know wether this looks ok. Then I include it in the repo ...
You may also take a look at: http://jspanel.de/documentation/ which is kinda like a getting started page

**Comment by gbaumgart** [comment]
@Flyer53 worked out of the box. Thank you very much!
