### ISSUE TITLE
cascading modal panels?

### ISSUE THREAD

**Issue by night507** [Flyer53/jsPanel#57]
Hello,
is there a way to cascade multiple modal panels which lock the previous panel?
So every Panel has its own backdrop. The problem is that the backdrop is closed when the second panel is closed, so the first panel isn't modal anymore.

![2016-03-17 14_06_21-nemetris web template - v0 5](https://cloud.githubusercontent.com/assets/15365969/13846730/81d087f4-ec49-11e5-924f-e410e45520fa.png)

Edit: I'm using the 3.0 Beta at the moment

**Comment by Flyer53** [comment]
@night507 
So far this is not a scenario I considered.
However, I made a little change to the latest Beta (you have to download it again) that will remove the modal backdrop only if the last modal jsPanel is closed. That's still only one backdrop and not a dedicated one for each modal panel, but might be ok for a start.

Real multiple modal panels where each new one has its own backdrop is something I have to think about some more ...

http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip

**Comment by night507** [comment]
@Flyer53 
I think i can work with that. I just need to lock the previous panel until the second one closes.
Thanks for the fast response.

**Comment by Flyer53** [comment]
@night507 
Ok, I worked on the beta a bit and now you can stack several modal jsPanels where each modal jsPanel has its own backdrop and will remove only its corresponding backdrop on close.
http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip
You need to exchange the js and the css file.
For a quick test just copy the code below ...
```javascript
$.jsPanel({
  paneltype: 'modal',
  headerTitle: 'modal jsPanel 1',
  callback: function () {
    $.jsPanel({
      paneltype: 'modal',
      headerTitle: 'modal jsPanel 2',
      callback: function () {
        $.jsPanel({
          paneltype: 'modal',
          headerTitle: 'modal jsPanel 3'
        });
      }
    });
  }
});
```
I need to do some more testing but it seems to work fine. Would appreciate some feedback vera much, thanks.

**Comment by night507** [comment]
@Flyer53 
The changes do seem to work fine. The only small problem i noticed is that the height of the backdrop does not resize, when the pagesize changes. (e.g. on console close or resize of the browser)

**Comment by Flyer53** [comment]
@night507 
Ok, I just tried on EDGE, IE11, FF, Chrome and Opera on my Windows 10 machine.
The only issue I can reproduce is the fixed backdrop height when the document height increases. That's because the backdrop gets the same height as the document when the backdrop is inserted. But I Have an idea I need to check first ...

**Comment by night507** [comment]
The newest beta update seems to fix the issue regarding the backdrop height.
So this issue can be closed.
