### ISSUE TITLE
Backdrop not auto resized with window resize in 2.6.x

### ISSUE THREAD

**Issue by genachka** [Flyer53/jsPanel#61]
When showing a panel with a backdrop covering the entire window, if the window's size increases, the backdrop doesn't automatically cover those additional areas.

**Comment by Flyer53** [comment]
Hi again :)
I guess you're talking about a modal panel. The only issue I see here is that the modal backdrop's height does not adjust when the pixel height of the document increases when the modal is already open. Is that what you mean?

**Comment by genachka** [comment]
Yup, exactly that issue. ;)

**Comment by Flyer53** [comment]
Ok, I have the same thing reported for version 3 beta. Looking into this soon ...

**Comment by genachka** [comment]
Another issue I encountered with back-drop, if modal dialog is open and
back-drop is displayed, and then a non modal dialog is also opened and then
closed, the modal dialog's back-drop is removed. For now I resolved it in a
callback of the 2nd dialog putting back the back-drop if it was there. I
thought I saw something recently about you keeping track of the back-drops
per dialog separately in 3.0?

So if you've solved it there, I'm ok with you not backporting a fix to 2.6.
And same goes for the back-drop resize issue, if it's solved in 3.0. :)

**Comment by Flyer53** [comment]
Well the latest beta of version 3 supports multiple modals where each modal has its own backdrop blocking underlying modals. Have to test it some more but seems to work fine :)

**Comment by Flyer53** [comment]
Once again I updated the jsPanel 3 beta. The height issue of the modal backdrop is solved, tested in FF, Chrome, Opera, EDGE and IE11

**Comment by genachka** [comment]
Thanks!
