### ISSUE TITLE
How to install beta with BOWER

### ISSUE THREAD

**Issue by whittssg** [Flyer53/jsPanel#62]
Hello,

How do i install the beta with bower? i tried: bower install jspanel#3.0.0-beta but it didnt work. thanks

**Comment by Flyer53** [comment]
Sorry, the beta is currently available only via the beta homepage.
http://beta.jspanel.de/downloads/jsPanel-3.0.0-Beta.zip

**Comment by whittssg** [comment]
No problem.. Thanks
