### ISSUE TITLE
onShown? 

### ISSUE THREAD

**Issue by gbaumgart** [Flyer53/jsPanel#65]
Hi,
how do i know that the panel is fully rendered? At the time of #callback the panel is in the DOM but not visible yet.

**Comment by gbaumgart** [comment]
i found $(elmtToPosition).animate({
                opacity: 1
            },{ duration: 300 });

I think this needs to be completed with an event that the panel is finally visible.

**Comment by Flyer53** [comment]
Hi again,

The event **jspanelloaded** is fired as soon as the panel is in the DOM.

But whatever function/s you add to **option.callback** are executed when everything else is ready, unless there are some asynchronous things. The only thing that's currently happening after executing the functions added with **option.callback** is adding jsPanel methods directly to the HTMLElement.

Did you run into some kind of problem?

The piece of code you reference is part of the positioning function. It might be better, I think, to remove the animation from there completely and leave any animation, if needed, to **option.show** only???

**Comment by gbaumgart** [comment]
yeah, I just realized this was about changing opacity only, so callback is the place to go. I don't mind the animation for now. 

Thanks for the heads up and sorry for the confusion. Solved for me ;-)

**Comment by Flyer53** [comment]
No problem ... always welcome :)
