### ISSUE TITLE
focus lost when closing panels

### ISSUE THREAD

**Issue by gbaumgart** [Flyer53/jsPanel#66]
I am not quit sure it's my responsibility but I think since you're managing multiple panels, its rather part of your code. 

Here is the thing: When you close a panel which has been opened from a previous panel, you'd usually set the focus to the last panel. 

I have the latest beta, do you know where this could be fixed? 

here a illustration:

![image](https://cloud.githubusercontent.com/assets/1205100/14789716/1da81bb4-0b0e-11e6-9507-150f827faec6.png)

However, I call panel.destroy on escape, cancel and ok. Is there a way to retrieve all panels (hopefully in the right order) so I can code this myself ?

thanks a lot,
guenter

**Comment by gbaumgart** [comment]
fixed on my side, never mind.

**Comment by Flyer53** [comment]
Hey Guenter,

Sounds good to me, however, would you mind sharing how you solved it? Just that I have a better understanding for the issue.

Concerning your question *.. is there a way to retrieve all panels ...*. The global jsPanel object maintains an array with the id values of all panels in the document in the order they are created:
**window.jsPanel.activePanels.list**
See http://beta.jspanel.de/#windowjspanel for some info

Regards, Stefan

**Comment by gbaumgart** [comment]
Hi,
it was pretty simply, In my wrapper (not public yet) I just track the instances in a sort of history and update this history by certain events (closed,shown,...) and set the focus on the current panel. Thanks for the heads up and thanks again!
