### ISSUE TITLE
[Suggestion] Fullscreen overlay as a jsPanel background

### ISSUE THREAD

**Issue by thecenz1** [Flyer53/jsPanel#67]
Hey, 

I was thinking of one option you could add. Sometimes when you want the user to focus on a specific modal, you add a greyish semi transparent fullscreen background that overlay the whole window except the modal. I think it would be a nice addition to your panel. :)

**Comment by Flyer53** [comment]
Hi again,

you're talking about a classic modal .... that's already there. You need to look under **option.paneltype**

For version 2.x http://jspanel.de/api/option/paneltype
For version 3 http://beta.jspanel.de/api/#option/paneltype

With version 3 you can even stack several modal panels.

Isn't that what you have in mind?

**Comment by thecenz1** [comment]
yes that's exactly it^^
Sorry I missed it from the doc.

**Comment by Flyer53** [comment]
Absolutely no problem,
I might have to make it more clear that it's a part of option.paneltype. Not your fault ;)
