### ISSUE TITLE
[NFR] New helper methods: unsmallify() and isSmallified()

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel#69]
Hello there,

1. If would be great to be able to query Panel for its current "**smallify**" state. `isSmallified()` would return a boolean.
2. It would be nice to break up `smallify()` to only smallify and let `unsmallify()` do what the name implies.

Right now since `smallify()` is a toggle, there's no way of knowing whether you are gonna do opposite of what you intend.

Thanks!

**Comment by Flyer53** [comment]
Did you check the panel property `status` which constantly logs the current status of a panel? 

http://jspanel.de/v2.6.2/api/property/status

**Comment by Flyer53** [comment]
@temuri416 
Since you didn't make any more comment for 5 months I consider this closed ...
