### ISSUE TITLE
Close window with touch

### ISSUE THREAD

**Issue by Speuta** [Flyer53/jsPanel#72]
On closing window with touch device, the event on the close button is propagated, and if there's another button below, it's clicked too.
Maybe a preventDefault or stopPropagation is missing on the touch event...

**Comment by Flyer53** [comment]
Hi there,
Well, jsPanel v2.x doesn't have touch support natively. Touch is implemented with the help of [jQuery UI Touch Punch](https://github.com/furf/jquery-ui-touch-punch), a jQuery plugin. There was no update for this plugin during the last 6 years now and I guess there won't be one in the future.

And by the way: jsPanel v2.x is pretty old now ... the current version being [4.10.2](https://github.com/Flyer53/jsPanel4). Maybe you should think about switching to the [current version](https://github.com/Flyer53/jsPanel4).

**Comment by Speuta** [comment]
Hi,
I'm currently on 4.10.2, thanks :)
If someone as the same problem, I resolved the bug by adding this in callback option:
``` javascript
callback: [
    function(panel){
        $(panel).find('.jsPanel-btn-close').on('touchstart', function(evt){
            evt.preventDefault(); 
            evt.stopPropagation();
            evt.stopImmediatePropagation();
            myPanel.close();
        });
    }
]
```

**Comment by Flyer53** [comment]
Ok, you posted under the v2 repo. So I thought you were using this old version.
However, can you tell me a bit more about the setup where you observed this issue? Device, OS, browser ... ? Do you observe it with the other controls as well?
All controls use either `mouseup`, `pointerup` or `touchend` events depending on supported APIs. So on a `touchstart` there shouldn't happen anything at all. And they all have a `preventDefault()` already.

Could it be that you inadvertantly activate a resize handle when closing the panel? They of course have to use `touchstart` or `pointerdown` and are close to the controls.

**Comment by Speuta** [comment]
Oh yes, sorry for the wrong repo !! Tell me is you prefer that I move this issue to jsPanel4.

Tested on an android device with google chrome, but you can also reproduce it on google chrome emulated devices functionality in devTool.

I've tested this on your [website](https://jspanel.de/).
Open it with a mobile device or just with emulated device in devTool, drag the window as the close button is just over the menu button, and press the close button: the Menu button is triggered too.

If `preventDefault()` is already called, maybe it's a `stopPropagation()` that's missing...

![jsPanel4](https://user-images.githubusercontent.com/23384732/83121709-f6a7f480-a0d2-11ea-8e43-772f55f2f39d.gif)
