### ISSUE TITLE
Position jsPanel as part of the flow (e.g. in grid)

### ISSUE THREAD

**Issue by stefan-reich** [Flyer53/jsPanel#75]
Hi,

I'd like to show a jsPanel as part of a grid layout, like here: https://gazelle.rocks/kb (the 6 boxes with class grid-item). But the panel should still be maximizable (resizable is optional). How to do this?

Thanks

**Comment by Flyer53** [comment]
Hi Stefan,
Before we go on with this issue a question from my side. You opened this issue in the jsPanel version 2 repo which is quite old. Did you consoder using the current [version 4.12.0](https://github.com/Flyer53/jsPanel4)?
Regards,
Stefan

**Comment by stefan-reich** [comment]
Oh wow. Didn't see the pointer to v4 on the README. I'll check it out, thanks

**Comment by Flyer53** [comment]
Sounds good to me,
But note that v4 is not a jQuery plugin anymore. So a few things are quite different.
Check it out and if something comes up ... you know where to find me ...
