### ISSUE TITLE
jspanel trigger 

### ISSUE THREAD

**Issue by eminserdar** [Flyer53/jsPanel#76]
hello How can I using  method  minimize page ? 
jspanel.normalize(); this method all pages trigger
I want only a page
jspanel.normalize("jsPanel_Owner_13-min"); but this not working
I'am using latest version 4.15.0
thank you

**Comment by Flyer53** [comment]
Hi there,
You say you use jsPanel v4.15.0. But you posted this issue in the repo of v2.x which is quite old and works differently as v4.x.

Please check out the docs at https://jspanel.de/#methods/overview and https://jspanel.de/#methods/minimize for v4.x
If you then still have questions post an issue in the appropriate repo or mail me (info@jspanel.de)

**Comment by Flyer53** [comment]
@eminserdar 
Since you did not respond to this in almost 2 months I consider this issue settled.
